# Label configuration for the repository
# This file is used by the label-sync workflow

- name: bug
  color: d73a4a
  description: Something isn't working

- name: documentation
  color: 0075ca
  description: Improvements or additions to documentation

- name: duplicate
  color: cfd3d7
  description: This issue or pull request already exists

- name: enhancement
  color: a2eeef
  description: New feature or request

- name: good first issue
  color: 7057ff
  description: Good for newcomers

- name: help wanted
  color: 008672
  description: Extra attention is needed

- name: invalid
  color: e4e669
  description: This doesn't seem right

- name: question
  color: d876e3
  description: Further information is requested

- name: wontfix
  color: ffffff
  description: This will not be worked on

- name: stale
  color: fef2c0
  description: This issue or PR is stale

- name: security
  color: ee0701
  description: Security related issue

- name: pinned
  color: fbca04
  description: This issue or PR should not be marked as stale

- name: ci/cd
  color: 0e8a16
  description: Related to CI/CD pipeline

- name: dependencies
  color: 0366d6
  description: Pull requests that update a dependency file

- name: performance
  color: 5319e7
  description: Performance improvements

- name: refactoring
  color: c5def5
  description: Code refactoring

- name: testing
  color: bfdadc
  description: Related to testing
